// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe1m_7UbLO-4TQv-qxCw-xhMv9Tddfw00',
    appId: '1:389833585115:web:e15734a74a3ef1ba3537fe',
    messagingSenderId: '389833585115',
    projectId: 'whatsappclone-19925',
    authDomain: 'whatsappclone-19925.firebaseapp.com',
    storageBucket: 'whatsappclone-19925.firebasestorage.app',
    measurementId: 'G-5WY4L80VZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEF9CgTusQVTn0mAaVr2AtvsSh9_CkeOU',
    appId: '1:389833585115:android:8ffa02b4cecdde2d3537fe',
    messagingSenderId: '389833585115',
    projectId: 'whatsappclone-19925',
    storageBucket: 'whatsappclone-19925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmsDozoKKXWFsZ3OOPm7bEeOUwL-5wp6M',
    appId: '1:389833585115:ios:7a5d81c10b31d9f63537fe',
    messagingSenderId: '389833585115',
    projectId: 'whatsappclone-19925',
    storageBucket: 'whatsappclone-19925.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmsDozoKKXWFsZ3OOPm7bEeOUwL-5wp6M',
    appId: '1:389833585115:ios:7a5d81c10b31d9f63537fe',
    messagingSenderId: '389833585115',
    projectId: 'whatsappclone-19925',
    storageBucket: 'whatsappclone-19925.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8CPNR9yVnOrqmR9dhg_fyHifNqXhVzis',
    appId: '1:389833585115:web:d6c6d46a1d7409253537fe',
    messagingSenderId: '389833585115',
    projectId: 'whatsappclone-19925',
    authDomain: 'whatsappclone-19925.firebaseapp.com',
    storageBucket: 'whatsappclone-19925.firebasestorage.app',
    measurementId: 'G-QJSBPCK1ZG',
  );
}
